import type { Metadata } from "next";
import { FooterNavigation } from "@/components/layout/footer-navigation";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body>
        {children}
        <FooterNavigation />
      </body>
    </html>
  );
}
